<%@ Page Title="" Language="C#" MasterPageFile="~/adm/Adm.master" AutoEventWireup="true" CodeBehind="cliente.aspx.cs" Inherits="SysAlmacen.adm.cliente" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <!--FORMULARIO DE REGISTRO DE CLIENTE-->
    <div class="card text-center">
        <div class="card-block p-0 p-sm-4 p-md-4 p-xl-4">
            <h2>Registrar Nuevo Cliente</h2>

            <form id="formUsuario" class="justify-content-center" runat="server">
                <div class="row">
                    <div class="form-group col-12">
                        <asp:TextBox runat="server" type="text" MaxLength="8" placeholder="Nombre Empresa" class="form-control" ID="txtEmpresa"></asp:TextBox>
                    </div>
                    <div class="form-group col-12">
                        <asp:TextBox runat="server" type="text" placeholder="Dueño" class="form-control" ID="txtDueño"></asp:TextBox>
                    </div>
                    <div class="form-group col-12">
                        <asp:TextBox runat="server" type="number" placeholder="RUC" class="form-control" ID="txtRUC"></asp:TextBox>
                    </div>
                    <div class="col-12 py-2">
                        <div class="row justify-content-center">
                            <asp:Button ID="btnRegistrarCliente" runat="server" Text="Registrar Cliente" class="btn bg-primary text-white col-6" OnClick="btnRegistrarCliente_Click" />
                        </div>

                    </div>
                </div>

                <div class="w3-container">
                    <!--LISTA DE CLIENTE-->
                    <h5>Clientes Registrados</h5>
                    <asp:GridView ID="ClienteList" runat="server" class="table table-striped table-light"
                        AllowPaging="true"
                        DataKeyNames="idCliente, estado"
                        AutoGenerateEditButton="True"
                        AutoGenerateDeleteButton="True"
                        OnRowUpdating="OnRowUpdating"
                        OnRowEditing="OnRowEditing"
                        OnRowCancelingEdit="OnRowCancelingEdit"
                        OnRowDeleting="OnRowDeleting">
                    </asp:GridView>
                </div>
                <hr>
            </form>
        </div>
    </div>
    <hr>
</asp:Content>
